# Site
repository: sproogen/resume-theme
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tristan Laidlow
title: Dyson Research Fellow
email: t.laidlow15@imperial.ac.uk
#website: tlaidlow.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
additional_links:
  - title: LinkedIn
    icon: fab fa-linkedin
    url: https://www.linkedin.com/in/tristan-laidlow
  - title: Google Scholar
    icon: fab fa-google
    url: https://scholar.google.com/citations?user=bmOi48IAAAAJ
  - title: ORCiD
    icon: fab fa-orcid
    url: https://orcid.org/0000-0002-3487-430X
  - title: CV
    icon: fas fa-file
    url: https://tlaidlow.github.io/files/cv.pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Biography
about_profile_image: images/tristan_laidlow.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a research fellow in the [Dyson Robotics Lab](https://www.imperial.ac.uk/dyson-robotics-lab) with [Prof. Andrew Davison](https://www.doc.ic.ac.uk/~ajd/) at [Imperial College London](https://www.imperial.ac.uk/).

  During my PhD, I worked under the supervision of [Dr. Stefan Leutenegger](https://www.professoren.tum.de/en/leutenegger-stefan) on making real-time dense visual SLAM more robust through the fusion of inertial data and learned depth priors. Previously, I completed a bachelor's degree in aerospace engineering from the [University of Toronto](https://www.utoronto.ca).

  My current research interests are in developing algorithms that enable robots to understand and interact with their environment. To this end, my research focuses on:
    - dense 3D reconstruction with informative geometric priors (learned or parametric),
    - efficient scene segmentation using sparse semantic annotations and neural fields, and
    - learning robust object manipulation policies.
#- estimating human motion from moving cameras.

content:
  - title: Publications
    layout: text
    content: |

      <div class="container intro-container">
        <div class="row clearfix">
          <div class="col-xs-12 col-sm-4 col-md-3 no-print">
            <img src="images/quadrics.png" alt="">
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9 col-print-12 content">
            <div class="title"> <p style="margin:0"><b> Simultaneous Localisation and Mapping with Quadric Surfaces </b></p> </div>
            <div class="author"> <p style="margin:0"> <u> Tristan Laidlow </u> and Andrew J. Davison </p> </div>
            <div class="conf"> <p style="margin:0"> <em> arXiv preprint </em> 2022 </p> </div>
            <div class="links"> <p style="margin:0">
              <a href="https://arxiv.org/abs/2103.12352"><mark>PDF</mark></a>
              <a href="https://www.youtube.com/watch?v=c-zkKGArl5Y"><mark>Video</mark></a>
              </p>
            </div>
          </div>
        </div>
      </div>

# Footer
footer_show_references: false
# references_title: 

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-cayman
