# Site
repository: sproogen/resume-theme
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tristan Laidlow
title: Dyson Research Fellow
email: t.laidlow15@imperial.ac.uk
#website: tlaidlow.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
additional_links:
  - title: LinkedIn
    icon: fab fa-linkedin
    url: https://www.linkedin.com/in/tristan-laidlow
  - title: Google Scholar
    icon: fab fa-google
    url: https://scholar.google.com/citations?user=bmOi48IAAAAJ
  - title: ORCiD
    icon: fab fa-orcid
    url: https://orcid.org/0000-0002-3487-430X
  - title: CV
    icon: fas fa-file
    url: https://tlaidlow.github.io/files/tristan_laidlow_cv.pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Biography
about_profile_image: images/tristan_laidlow.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a research fellow in the [Dyson Robotics Lab](https://www.imperial.ac.uk/dyson-robotics-lab) with [Prof. Andrew Davison](https://www.doc.ic.ac.uk/~ajd/) at [Imperial College London](https://www.imperial.ac.uk/).

  During my PhD, I worked under the supervision of [Dr. Stefan Leutenegger](https://www.professoren.tum.de/en/leutenegger-stefan) on making real-time dense visual SLAM more robust through the fusion of inertial data and learned depth priors. Previously, I completed a bachelor's degree in aerospace engineering from the [University of Toronto](https://www.utoronto.ca).

  My current research interests are in developing algorithms that enable robots to understand and interact with their environment. To this end, my research focuses on:
    - dense 3D reconstruction with informative geometric priors (learned or parametric),
    - efficient scene segmentation using sparse semantic annotations and neural fields, and
    - learning robust object manipulation policies.
#- estimating human motion from moving cameras.

content:
  - title: Publications
    layout: text
    content: |

      <div class="container intro-container">
        <div class="row clearfix">
          <div class="col-xs-12 col-sm-4 col-md-3 no-print">
            <img src="images/quadrics.png" alt="">
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9 col-print-12 content">
            <div class="title"> <p style="margin:0"> <b>Simultaneous Localisation and Mapping with Quadric Surfaces</b> </p> </div>
            <div class="author"> <p style="margin:0"> <u>Tristan Laidlow</u> and Andrew J. Davison </p> </div>
            <div class="conf"> <p style="margin:0"> <em>arXiv preprint</em> 2022 </p> </div>
            <div class="links"> <p style="margin:0">
              <a href="https://arxiv.org/pdf/2203.08040.pdf"><mark>PDF</mark></a>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="container intro-container">
        <div class="row clearfix">
          <div class="col-xs-12 col-sm-4 col-md-3 no-print">
            <img src="images/c2f.jpg" alt="">
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9 col-print-12 content">
            <div class="title"> <p style="margin:0"> <b>Coarse-to-Fine Q-Attention: Efficient Learning for Visual Robotic Manipulation via Discretisation</b> </p> </div>
            <div class="author"> <p style="margin:0"> Stephen James, Kentaro Wada, <u>Tristan Laidlow</u>, and Andrew J. Davison </p> </div>
            <div class="conf"> <p style="margin:0"> <em>CVPR</em> 2022 (Oral) </p> </div>
            <div class="links"> <p style="margin:0">
              <a href="https://sites.google.com/view/c2f-q-attention"><mark>Project</mark></a>
              <a href="https://arxiv.org/pdf/2106.12534.pdf"><mark>PDF</mark></a>
              <a href="https://github.com/stepjam/ARM"><mark>Code</mark></a>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="container intro-container">
        <div class="row clearfix">
          <div class="col-xs-12 col-sm-4 col-md-3 no-print">
            <img src="images/ilabel.png" alt="">
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9 col-print-12 content">
            <div class="title"> <p style="margin:0"> <b>iLabel: Interactive Neural Scene Labelling</b> </p> </div>
            <div class="author"> <p style="margin:0"> Shuaifeng Zhi*, Edgar Sucar*, Andre Mouton, Iain Haughton, <u>Tristan Laidlow</u>, and Andrew J. Davison </p> </div>
            <div class="denotes"> <p style="margin:0"> (* denotes equal contribution) </p> </div>
            <div class="conf"> <p style="margin:0"> <em>arXiv preprint</em> 2021 </p> </div>
            <div class="links"> <p style="margin:0">
              <a href="https://edgarsucar.github.io/ilabel/"><mark>Project</mark></a>
              <a href="https://arxiv.org/pdf/2111.14637.pdf"><mark>PDF</mark></a>
              <a href="https://youtu.be/bL7RZaMhRbk"><mark>Video</mark></a>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="container intro-container">
        <div class="row clearfix">
          <div class="col-xs-12 col-sm-4 col-md-3 no-print">
            <img src="images/semantic_nerf.png" alt="">
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9 col-print-12 content">
            <div class="title"> <p style="margin:0"> <b>In-Place Scene Labelling and Understanding with Implicit Scene Representation</b> </p> </div>
            <div class="author"> <p style="margin:0"> Shuaifeng Zhi, <u>Tristan Laidlow</u>, Stefan Leutenegger, and Andrew J. Davison </p> </div>
            <div class="conf"> <p style="margin:0"> <em>ICCV</em> 2021 (Oral) </p> </div>
            <div class="links"> <p style="margin:0">
              <a href="https://shuaifengzhi.com/Semantic-NeRF/"><mark>Project</mark></a>
              <a href="https://arxiv.org/pdf/2103.15875.pdf"><mark>PDF</mark></a>
              <a href="https://www.youtube.com/watch?v=FpShWO7LVbM"><mark>Video</mark></a>
              <a href="https://github.com/Harry-Zhi/semantic_nerf/"><mark>Code</mark></a>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="container intro-container">
        <div class="row clearfix">
          <div class="col-xs-12 col-sm-4 col-md-3 no-print">
            <img src="images/simstack.png" alt="">
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9 col-print-12 content">
            <div class="title"> <p style="margin:0"> <b>SIMstack: A Generative Shape and Instance Model for Unordered Object Stacks</b> </p> </div>
            <div class="author"> <p style="margin:0"> Zoe Landgraf, Raluca Scona, <u>Tristan Laidlow</u>, Stephen James, Stefan Leutenegger, and Andrew J. Davison </p> </div>
            <div class="conf"> <p style="margin:0"> <em>ICCV</em> 2021 </p> </div>
            <div class="links"> <p style="margin:0">
              <a href="https://zoelandgraf.github.io/SIMstack/"><mark>Project</mark></a>
              <a href="https://arxiv.org/pdf/2103.16442.pdf"><mark>PDF</mark></a>
              <a href="https://www.youtube.com/watch?v=6IruTME-EXM"><mark>Video</mark></a>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="container intro-container">
        <div class="row clearfix">
          <div class="col-xs-12 col-sm-4 col-md-3 no-print">
            <img src="images/towards.gif" alt="">
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9 col-print-12 content">
            <div class="title"> <p style="margin:0"> <b>Towards the Probabilistic Fusion of Learned Priors into Standard Pipelines for 3D Reconstruction</b> </p> </div>
            <div class="author"> <p style="margin:0"> <u>Tristan Laidlow</u>, Jan Czarnowski, Andrea Nicastro, Ronald Clark, and Stefan Leutenegger </p> </div>
            <div class="conf"> <p style="margin:0"> <em>ICRA</em> 2020 </p> </div>
            <div class="links"> <p style="margin:0">
              <a href="https://www.imperial.ac.uk/media/imperial-college/research-centres-and-groups/dyson-robotics-lab/Laidlow_ICRA2020.pdf"><mark>PDF</mark></a>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="container intro-container">
        <div class="row clearfix">
          <div class="col-xs-12 col-sm-4 col-md-3 no-print">
            <img src="images/deepfactors.gif" alt="">
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9 col-print-12 content">
            <div class="title"> <p style="margin:0"> <b>DeepFactors: Real-Time Probabilistic Dense Monocular SLAM</b> </p> </div>
            <div class="author"> <p style="margin:0"> Jan Czarnowski, <u>Tristan Laidlow</u>, Ronald Clark, and Andrew J. Davison </p> </div>
            <div class="conf"> <p style="margin:0"> <em>RA-L</em> 2020 </p> </div>
            <div class="links"> <p style="margin:0">
              <a href="https://arxiv.org/pdf/2001.05049.pdf"><mark>PDF</mark></a>
              <a href="https://www.youtube.com/watch?v=htnRuGKZmZw"><mark>Video</mark></a>
              <a href="https://github.com/jczarnowski/DeepFactors"><mark>Code</mark></a>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="container intro-container">
        <div class="row clearfix">
          <div class="col-xs-12 col-sm-4 col-md-3 no-print">
            <img src="images/deepfusion.png" alt="">
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9 col-print-12 content">
            <div class="title"> <p style="margin:0"> <b>DeepFusion: Real-Time Dense 3D Reconstruction for Monocular SLAM using Single-View Depth and Gradient Predictions</b> </p> </div>
            <div class="author"> <p style="margin:0"> <u>Tristan Laidlow</u>, Jan Czarnowski, and Stefan Leutenegger </p> </div>
            <div class="conf"> <p style="margin:0"> <em>ICRA</em> 2019 </p> </div>
            <div class="links"> <p style="margin:0">
              <a href="https://spiral.imperial.ac.uk/bitstream/10044/1/70868/4/DeepFusion_ICRA2019_CameraReady.pdf"><mark>PDF</mark></a>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="container intro-container">
        <div class="row clearfix">
          <div class="col-xs-12 col-sm-4 col-md-3 no-print">
            <img src="images/meshes.gif" alt="">
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9 col-print-12 content">
            <div class="title"> <p style="margin:0"> <b>Learning Meshes for Dense Visual SLAM</b> </p> </div>
            <div class="author"> <p style="margin:0"> Michael Bloesch, <u>Tristan Laidlow</u>, Ronald Clark, Stefan Leutenegger, and Andrew J. Davison </p> </div>
            <div class="conf"> <p style="margin:0"> <em>ICCV</em> 2019 </p> </div>
            <div class="links"> <p style="margin:0">
              <a href="https://openaccess.thecvf.com/content_ICCV_2019/papers/Bloesch_Learning_Meshes_for_Dense_Visual_SLAM_ICCV_2019_paper.pdf"><mark>PDF</mark></a>
              <a href="https://www.youtube.com/watch?v=nClSHUovDfU"><mark>Video</mark></a>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="container intro-container">
        <div class="row clearfix">
          <div class="col-xs-12 col-sm-4 col-md-3 no-print">
            <img src="images/rgbdi.png" alt="">
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9 col-print-12 content">
            <div class="title"> <p style="margin:0"> <b>Dense RGB-D-Inertial SLAM with Map Deformations</b> </p> </div>
            <div class="author"> <p style="margin:0"> <u>Tristan Laidlow</u>, Michael Bloesch, Wenbin Li, and Stefan Leutenegger </p> </div>
            <div class="conf"> <p style="margin:0"> <em>IROS</em> 2017 </p> </div>
            <div class="links"> <p style="margin:0">
              <a href="https://spiral.imperial.ac.uk/bitstream/10044/1/51141/4/IROS2017_Laidlow.pdf"><mark>PDF</mark></a>
              <a href="https://www.youtube.com/watch?v=-gUdQ0cxDh0"><mark>Video</mark></a>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="container intro-container">
        <div class="row clearfix">
          <div class="col-xs-12 col-sm-4 col-md-3 no-print">
            <img src="images/primer.png" alt="">
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9 col-print-12 content">
            <div class="title"> <p style="margin:0"> <b>A Primer on the Differential Calculus of 3D Orientations</b> </p> </div>
            <div class="author"> <p style="margin:0"> Michael Bloesch, Hannes Sommer, <u>Tristan Laidlow</u>, Michael Burri, Gabriel Nuetzi, Peter Fankhauser, Dario Bellicoso, Christian Gehring, Stefan Leutenegger, Marco Hutter, and Roland Siegwart </p> </div>
            <div class="conf"> <p style="margin:0"> <em>arXiv preprint</em> 2016 </p> </div>
            <div class="links"> <p style="margin:0">
              <a href="https://arxiv.org/pdf/1606.05285.pdf"><mark>PDF</mark></a>
              </p>
            </div>
          </div>
        </div>
      </div>

# Footer
footer_show_references: false
# references_title: 

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-cayman
